export type ThemeColors = {
  background: string
  foreground: string
  card: string
  cardForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  muted: string
  mutedForeground: string
  accent: string
  accentForeground: string
  border: string
  input: string
  ring: string
  destructive: string
  statusGreen: string
  statusAmber: string
  statusRed: string
}

export type AppTheme = {
  id: string
  name: string
  description: string
  light: ThemeColors
  dark: ThemeColors
}

export const themes: AppTheme[] = [
  {
    id: "aca",
    name: "ACA",
    description: "Navy and crimson, bold institutional",
    light: {
      background: "#ffffff",
      foreground: "#0f1b4c",
      card: "#f7f8fc",
      cardForeground: "#0f1b4c",
      primary: "#c41230",
      primaryForeground: "#ffffff",
      secondary: "#edf0f8",
      secondaryForeground: "#0f1b4c",
      muted: "#edf0f8",
      mutedForeground: "#485d8a",
      accent: "#edf0f8",
      accentForeground: "#0f1b4c",
      border: "#d0d8ee",
      input: "#d0d8ee",
      ring: "#c41230",
      destructive: "#a00f28",
      statusGreen: "#156940",
      statusAmber: "#8a5600",
      statusRed: "#a00f28",
    },
    dark: {
      background: "#080d1e",
      foreground: "#e8ecf8",
      card: "#0f1b3a",
      cardForeground: "#e8ecf8",
      primary: "#e8203e",
      primaryForeground: "#ffffff",
      secondary: "#162040",
      secondaryForeground: "#e8ecf8",
      muted: "#162040",
      mutedForeground: "#8a9ac8",
      accent: "#162040",
      accentForeground: "#e8ecf8",
      border: "#1e2e54",
      input: "#1e2e54",
      ring: "#e8203e",
      destructive: "#e8203e",
      statusGreen: "#2aaa6a",
      statusAmber: "#e8a020",
      statusRed: "#e8203e",
    },
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    description: "Neutral product-grade, single blue accent",
    light: {
      background: "#ffffff",
      foreground: "#171717",
      card: "#fafafa",
      cardForeground: "#171717",
      primary: "#2563eb",
      primaryForeground: "#ffffff",
      secondary: "#f5f5f5",
      secondaryForeground: "#171717",
      muted: "#f5f5f5",
      mutedForeground: "#737373",
      accent: "#f5f5f5",
      accentForeground: "#171717",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#2563eb",
      destructive: "#dc2626",
      statusGreen: "#15803d",
      statusAmber: "#92400e",
      statusRed: "#b91c1c",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#ededed",
      card: "#171717",
      cardForeground: "#ededed",
      primary: "#3b82f6",
      primaryForeground: "#0a0a0a",
      secondary: "#262626",
      secondaryForeground: "#ededed",
      muted: "#262626",
      mutedForeground: "#a3a3a3",
      accent: "#262626",
      accentForeground: "#ededed",
      border: "#262626",
      input: "#262626",
      ring: "#3b82f6",
      destructive: "#ef4444",
      statusGreen: "#22c55e",
      statusAmber: "#f59e0b",
      statusRed: "#ef4444",
    },
  },
  {
    id: "ocean-depths",
    name: "Ocean Depths",
    description: "Professional maritime, navy and teal",
    light: {
      background: "#f1faee",
      foreground: "#1a2332",
      card: "#ffffff",
      cardForeground: "#1a2332",
      primary: "#2d8b8b",
      primaryForeground: "#ffffff",
      secondary: "#e8f4f4",
      secondaryForeground: "#1a2332",
      muted: "#e8f4f4",
      mutedForeground: "#4a6670",
      accent: "#e8f4f4",
      accentForeground: "#1a2332",
      border: "#c8dede",
      input: "#c8dede",
      ring: "#2d8b8b",
      destructive: "#dc2626",
      statusGreen: "#1f7373",
      statusAmber: "#92400e",
      statusRed: "#b91c1c",
    },
    dark: {
      background: "#0f1720",
      foreground: "#f1faee",
      card: "#1a2332",
      cardForeground: "#f1faee",
      primary: "#2d8b8b",
      primaryForeground: "#f1faee",
      secondary: "#223344",
      secondaryForeground: "#f1faee",
      muted: "#223344",
      mutedForeground: "#a8dadc",
      accent: "#223344",
      accentForeground: "#f1faee",
      border: "#2a3a4a",
      input: "#2a3a4a",
      ring: "#2d8b8b",
      destructive: "#ef4444",
      statusGreen: "#2d8b8b",
      statusAmber: "#f59e0b",
      statusRed: "#ef4444",
    },
  },
  {
    id: "sunset-boulevard",
    name: "Sunset Boulevard",
    description: "Warm oranges and coral, creative energy",
    light: {
      background: "#fffbf5",
      foreground: "#264653",
      card: "#ffffff",
      cardForeground: "#264653",
      primary: "#e76f51",
      primaryForeground: "#ffffff",
      secondary: "#fef0e6",
      secondaryForeground: "#264653",
      muted: "#fef0e6",
      mutedForeground: "#5a7a8a",
      accent: "#fef0e6",
      accentForeground: "#264653",
      border: "#f4d5c0",
      input: "#f4d5c0",
      ring: "#e76f51",
      destructive: "#dc2626",
      statusGreen: "#1a7a6e",
      statusAmber: "#8a5a20",
      statusRed: "#c45a42",
    },
    dark: {
      background: "#1a1f24",
      foreground: "#faf5ef",
      card: "#264653",
      cardForeground: "#faf5ef",
      primary: "#e76f51",
      primaryForeground: "#ffffff",
      secondary: "#2f3d47",
      secondaryForeground: "#faf5ef",
      muted: "#2f3d47",
      mutedForeground: "#b0bec5",
      accent: "#2f3d47",
      accentForeground: "#faf5ef",
      border: "#3a4f5c",
      input: "#3a4f5c",
      ring: "#e76f51",
      destructive: "#ef4444",
      statusGreen: "#2dd4bf",
      statusAmber: "#f4a261",
      statusRed: "#e76f51",
    },
  },
  {
    id: "forest-canopy",
    name: "Forest Canopy",
    description: "Earth greens and ivory, grounded natural",
    light: {
      background: "#faf9f6",
      foreground: "#2d4a2b",
      card: "#ffffff",
      cardForeground: "#2d4a2b",
      primary: "#2d4a2b",
      primaryForeground: "#faf9f6",
      secondary: "#eef2eb",
      secondaryForeground: "#2d4a2b",
      muted: "#eef2eb",
      mutedForeground: "#7d8471",
      accent: "#eef2eb",
      accentForeground: "#2d4a2b",
      border: "#d4dace",
      input: "#d4dace",
      ring: "#2d4a2b",
      destructive: "#dc2626",
      statusGreen: "#2d4a2b",
      statusAmber: "#6b5d2e",
      statusRed: "#b91c1c",
    },
    dark: {
      background: "#141a14",
      foreground: "#eef2eb",
      card: "#1e2a1e",
      cardForeground: "#eef2eb",
      primary: "#5a8a58",
      primaryForeground: "#eef2eb",
      secondary: "#283828",
      secondaryForeground: "#eef2eb",
      muted: "#283828",
      mutedForeground: "#a4ac86",
      accent: "#283828",
      accentForeground: "#eef2eb",
      border: "#344034",
      input: "#344034",
      ring: "#5a8a58",
      destructive: "#ef4444",
      statusGreen: "#5a8a58",
      statusAmber: "#a4ac86",
      statusRed: "#ef4444",
    },
  },
  {
    id: "modern-minimalist",
    name: "Modern Minimalist",
    description: "Charcoal and slate, clean versatile",
    light: {
      background: "#ffffff",
      foreground: "#36454f",
      card: "#fafafa",
      cardForeground: "#36454f",
      primary: "#36454f",
      primaryForeground: "#ffffff",
      secondary: "#f0f0f0",
      secondaryForeground: "#36454f",
      muted: "#f0f0f0",
      mutedForeground: "#708090",
      accent: "#f0f0f0",
      accentForeground: "#36454f",
      border: "#d3d3d3",
      input: "#d3d3d3",
      ring: "#36454f",
      destructive: "#dc2626",
      statusGreen: "#3a7a4a",
      statusAmber: "#7a6420",
      statusRed: "#a03636",
    },
    dark: {
      background: "#121618",
      foreground: "#e8eaed",
      card: "#1c2024",
      cardForeground: "#e8eaed",
      primary: "#708090",
      primaryForeground: "#121618",
      secondary: "#262a2e",
      secondaryForeground: "#e8eaed",
      muted: "#262a2e",
      mutedForeground: "#8a9aaa",
      accent: "#262a2e",
      accentForeground: "#e8eaed",
      border: "#333a40",
      input: "#333a40",
      ring: "#708090",
      destructive: "#ef4444",
      statusGreen: "#5aaa6e",
      statusAmber: "#d4a84a",
      statusRed: "#ef4444",
    },
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    description: "Mustard and terracotta, warm autumnal",
    light: {
      background: "#fdfaf5",
      foreground: "#4a403a",
      card: "#ffffff",
      cardForeground: "#4a403a",
      primary: "#c1666b",
      primaryForeground: "#ffffff",
      secondary: "#f5ede4",
      secondaryForeground: "#4a403a",
      muted: "#f5ede4",
      mutedForeground: "#8a7a6e",
      accent: "#f5ede4",
      accentForeground: "#4a403a",
      border: "#e0d0c0",
      input: "#e0d0c0",
      ring: "#c1666b",
      destructive: "#dc2626",
      statusGreen: "#4a6e32",
      statusAmber: "#7a5c00",
      statusRed: "#a04a4e",
    },
    dark: {
      background: "#1a1614",
      foreground: "#f0e8e0",
      card: "#2a2420",
      cardForeground: "#f0e8e0",
      primary: "#c1666b",
      primaryForeground: "#f0e8e0",
      secondary: "#342e28",
      secondaryForeground: "#f0e8e0",
      muted: "#342e28",
      mutedForeground: "#d4b896",
      accent: "#342e28",
      accentForeground: "#f0e8e0",
      border: "#443830",
      input: "#443830",
      ring: "#c1666b",
      destructive: "#ef4444",
      statusGreen: "#7aaa5a",
      statusAmber: "#f4a900",
      statusRed: "#c1666b",
    },
  },
  {
    id: "arctic-frost",
    name: "Arctic Frost",
    description: "Ice blue and steel, crisp precision",
    light: {
      background: "#fafcff",
      foreground: "#1e2a3a",
      card: "#ffffff",
      cardForeground: "#1e2a3a",
      primary: "#4a6fa5",
      primaryForeground: "#ffffff",
      secondary: "#eaf0f8",
      secondaryForeground: "#1e2a3a",
      muted: "#eaf0f8",
      mutedForeground: "#6a8aaa",
      accent: "#eaf0f8",
      accentForeground: "#1e2a3a",
      border: "#d4e4f7",
      input: "#d4e4f7",
      ring: "#4a6fa5",
      destructive: "#dc2626",
      statusGreen: "#2e7258",
      statusAmber: "#7a6008",
      statusRed: "#b91c1c",
    },
    dark: {
      background: "#0c1018",
      foreground: "#e4eaf2",
      card: "#141c28",
      cardForeground: "#e4eaf2",
      primary: "#4a6fa5",
      primaryForeground: "#e4eaf2",
      secondary: "#1e2a3a",
      secondaryForeground: "#e4eaf2",
      muted: "#1e2a3a",
      mutedForeground: "#8aaace",
      accent: "#1e2a3a",
      accentForeground: "#e4eaf2",
      border: "#2a3a50",
      input: "#2a3a50",
      ring: "#4a6fa5",
      destructive: "#ef4444",
      statusGreen: "#4aaa7a",
      statusAmber: "#e0b62a",
      statusRed: "#ef4444",
    },
  },
  {
    id: "desert-rose",
    name: "Desert Rose",
    description: "Dusty rose and clay, soft sophisticated",
    light: {
      background: "#fdfaf8",
      foreground: "#5d2e46",
      card: "#ffffff",
      cardForeground: "#5d2e46",
      primary: "#b87d6d",
      primaryForeground: "#ffffff",
      secondary: "#f5ece8",
      secondaryForeground: "#5d2e46",
      muted: "#f5ece8",
      mutedForeground: "#9a7a70",
      accent: "#f5ece8",
      accentForeground: "#5d2e46",
      border: "#e8d5c4",
      input: "#e8d5c4",
      ring: "#b87d6d",
      destructive: "#dc2626",
      statusGreen: "#4a7050",
      statusAmber: "#7a6008",
      statusRed: "#b91c1c",
    },
    dark: {
      background: "#18100e",
      foreground: "#f0e8e4",
      card: "#241a18",
      cardForeground: "#f0e8e4",
      primary: "#d4a5a5",
      primaryForeground: "#18100e",
      secondary: "#302420",
      secondaryForeground: "#f0e8e4",
      muted: "#302420",
      mutedForeground: "#c0a090",
      accent: "#302420",
      accentForeground: "#f0e8e4",
      border: "#443430",
      input: "#443430",
      ring: "#d4a5a5",
      destructive: "#ef4444",
      statusGreen: "#7aaa7a",
      statusAmber: "#e0b62a",
      statusRed: "#ef4444",
    },
  },
  {
    id: "tech-innovation",
    name: "Tech Innovation",
    description: "Electric blue, bold modern tech",
    light: {
      background: "#ffffff",
      foreground: "#1e1e1e",
      card: "#f8f9fa",
      cardForeground: "#1e1e1e",
      primary: "#0066ff",
      primaryForeground: "#ffffff",
      secondary: "#eef2ff",
      secondaryForeground: "#1e1e1e",
      muted: "#eef2ff",
      mutedForeground: "#6a6a7a",
      accent: "#eef2ff",
      accentForeground: "#1e1e1e",
      border: "#d0d8e8",
      input: "#d0d8e8",
      ring: "#0066ff",
      destructive: "#dc2626",
      statusGreen: "#008050",
      statusAmber: "#8a5800",
      statusRed: "#b91c1c",
    },
    dark: {
      background: "#0a0a0e",
      foreground: "#f0f0f4",
      card: "#1e1e24",
      cardForeground: "#f0f0f4",
      primary: "#0066ff",
      primaryForeground: "#ffffff",
      secondary: "#1a1a24",
      secondaryForeground: "#f0f0f4",
      muted: "#1a1a24",
      mutedForeground: "#8888aa",
      accent: "#1a1a24",
      accentForeground: "#f0f0f4",
      border: "#2a2a38",
      input: "#2a2a38",
      ring: "#0066ff",
      destructive: "#ef4444",
      statusGreen: "#00cc77",
      statusAmber: "#ffaa22",
      statusRed: "#ef4444",
    },
  },
  {
    id: "botanical-garden",
    name: "Botanical Garden",
    description: "Fern green and marigold, fresh organic",
    light: {
      background: "#f5f3ed",
      foreground: "#2a3a2a",
      card: "#ffffff",
      cardForeground: "#2a3a2a",
      primary: "#4a7c59",
      primaryForeground: "#ffffff",
      secondary: "#eef2ea",
      secondaryForeground: "#2a3a2a",
      muted: "#eef2ea",
      mutedForeground: "#6a7a6a",
      accent: "#eef2ea",
      accentForeground: "#2a3a2a",
      border: "#d0dac8",
      input: "#d0dac8",
      ring: "#4a7c59",
      destructive: "#b7472a",
      statusGreen: "#3a6848",
      statusAmber: "#7a5c10",
      statusRed: "#9a3a22",
    },
    dark: {
      background: "#0e120e",
      foreground: "#e8ece4",
      card: "#1a201a",
      cardForeground: "#e8ece4",
      primary: "#5a9a6a",
      primaryForeground: "#0e120e",
      secondary: "#242a24",
      secondaryForeground: "#e8ece4",
      muted: "#242a24",
      mutedForeground: "#8aaa8a",
      accent: "#242a24",
      accentForeground: "#e8ece4",
      border: "#303830",
      input: "#303830",
      ring: "#5a9a6a",
      destructive: "#ef4444",
      statusGreen: "#5a9a6a",
      statusAmber: "#f9a620",
      statusRed: "#ef4444",
    },
  },
  {
    id: "midnight-galaxy",
    name: "Midnight Galaxy",
    description: "Deep purple and lavender, dramatic cosmic",
    light: {
      background: "#faf8ff",
      foreground: "#2b1e3e",
      card: "#ffffff",
      cardForeground: "#2b1e3e",
      primary: "#4a4e8f",
      primaryForeground: "#ffffff",
      secondary: "#f0ecf8",
      secondaryForeground: "#2b1e3e",
      muted: "#f0ecf8",
      mutedForeground: "#7a6a9a",
      accent: "#f0ecf8",
      accentForeground: "#2b1e3e",
      border: "#d8d0e8",
      input: "#d8d0e8",
      ring: "#4a4e8f",
      destructive: "#dc2626",
      statusGreen: "#456878",
      statusAmber: "#7a6030",
      statusRed: "#b91c1c",
    },
    dark: {
      background: "#0e0a14",
      foreground: "#e6e6fa",
      card: "#1a1428",
      cardForeground: "#e6e6fa",
      primary: "#7a7ec0",
      primaryForeground: "#0e0a14",
      secondary: "#241e38",
      secondaryForeground: "#e6e6fa",
      muted: "#241e38",
      mutedForeground: "#a490c2",
      accent: "#241e38",
      accentForeground: "#e6e6fa",
      border: "#342e4e",
      input: "#342e4e",
      ring: "#7a7ec0",
      destructive: "#ef4444",
      statusGreen: "#6a9aaa",
      statusAmber: "#ccaa5a",
      statusRed: "#ef4444",
    },
  },
]

export const DEFAULT_THEME_ID = "aca"

export function getThemeById(id: string): AppTheme {
  return themes.find((t) => t.id === id) ?? themes[0]
}
