/**
 * State-scoped DMV forms for Actions (Step 4).
 * Generated by `npm run import:forms` from `data/Titles Forms and Letters.xlsx`.
 *
 * Workbook columns (Forms sheet): C = state, D/F/H/J = form slots, K = Notarized,
 * L = Title required, M = Security agreement required, N = notes.
 */

import formsData from "@/lib/generated/state-forms.json"

export interface StateFormDefinition {
  id: string
  state: string
  stateName: string
  team: string
  process: string
  formName: string
  notarized: string
  titleRequired: string
  securityAgreementRequired: string
  notes: string
  sourceSheet: string
  sourceRow: number
}

export interface LetterDefinition {
  id: string
  team: string
  process: string
  letterName: string
  recipient: string
  notesAlice: string
  sourceSheet: string
  sourceRow: number
}

const forms = formsData.forms as StateFormDefinition[]
const letters = formsData.letters as LetterDefinition[]

export function normalizeStateCode(raw: string | null | undefined): string {
  if (!raw || !raw.trim()) return ""
  return raw.trim().toUpperCase().slice(0, 2)
}

export function getFormsForState(titleState: string): StateFormDefinition[] {
  const s = normalizeStateCode(titleState)
  if (!s) return []
  return forms.filter((f) => f.state === s)
}

/** Specialty letters (Letters sheet) — use for future Outbound / letter flows */
export function getAllLetters(): LetterDefinition[] {
  return [...letters]
}

export const stateFormsMeta = {
  generatedAt: formsData.generatedAt,
  sourceFile: formsData.sourceFile,
  description: formsData.description,
}
